# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(744, 630)
        self.text = QtWidgets.QLabel(Form)
        self.text.setGeometry(QtCore.QRect(80, 230, 211, 51))
        self.text.setObjectName("text")
        self.addButton = QtWidgets.QPushButton(Form)
        self.addButton.setGeometry(QtCore.QRect(90, 560, 93, 28))
        self.addButton.setObjectName("addButton")
        self.reviseButton = QtWidgets.QPushButton(Form)
        self.reviseButton.setGeometry(QtCore.QRect(340, 560, 93, 28))
        self.reviseButton.setObjectName("reviseButton")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(355, 61, 361, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(50, 70, 161, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.searchButton = QtWidgets.QPushButton(Form)
        self.searchButton.setGeometry(QtCore.QRect(230, 70, 81, 28))
        self.searchButton.setObjectName("searchButton")
        self.deleteButton = QtWidgets.QPushButton(Form)
        self.deleteButton.setGeometry(QtCore.QRect(220, 560, 93, 28))
        self.deleteButton.setObjectName("deleteButton")
        self.borrowButton = QtWidgets.QPushButton(Form)
        self.borrowButton.setGeometry(QtCore.QRect(520, 560, 93, 28))
        self.borrowButton.setObjectName("borrowButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.text.setText(_translate("Form", "TextLabel"))
        self.addButton.setText(_translate("Form", "新增"))
        self.reviseButton.setText(_translate("Form", "修改"))
        self.searchButton.setText(_translate("Form", "OK"))
        self.deleteButton.setText(_translate("Form", "刪除"))
        self.borrowButton.setText(_translate("Form", "借物"))
